# This is a basic workflow to help you get started with Actions

name: Test & Upload to TestPyPI

# Controls when the action will run. 
on:
  release:
    types: [created]
  # Triggers the workflow on push to the master branch
  #pull_request:
  #push:
  #  tag: "*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Installs and upgrades pip, installs other dependencies and installs the package from setup.py
      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          AVI_VERSION=`python ./python/version.py`
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install setuptools wheel twine
          # If requirements.txt exists, install from it
          cd python
          ./create_sdk_pip_packages.sh sdk
          ./create_sdk_pip_packages.sh migrationtools
          #./create_sdk_pypi.sh sdk
          echo "AVI VERSION=== $AVI_VERSION"
          ls dist/
          mv dist/avimigrationtools-21.1.1b1.tar.gz ../avimigrationtools-21.1.1b1.tar.gz
          echo "Java Version: " 
          echo ${GITHUB_REF##*/} | cut -d - -f 2
          #mv dist/avimigrationtools-$AVI_VERSION.tar.gz ../avimigrationtools-$AVI_VERSION.tar.gz
          #mv dist/avisdk-$AVI_VERSION.tar.gz ../avisdk-$AVI_VERSION.tar.gz
          #mv dist/python-avisdk_0_all.deb ../avisdk-$AVI_VERSION.deb
          #mv dist/avisdk-$AVI_VERSION-1.noarch.rpm ../avisdk-$AVI_VERSION.rpm
          #mv dist/avimigrationtools-$AVI_VERSION.tar.gz ../avimigrationtools-$AVI_VERSION.tar.gz
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Avi API SDK pip package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.update_release.outputs.upload_url }}
          asset_path: avimigrationtools-21.1.1b1.tar.gz
          asset_name: pip-package-avisdk-$AVI_VERSION
          asset_content_type: application/gzip 


